Vagrant.configure(2) do |config|
  config.vm.box = "CentOS7.0_x86_64"
  config.vm.box_url = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.0_chef-provisionerless.box"

  config.vm.network "private_network", ip: "192.168.33.100"
  config.vm.hostname = "salmon"

  config.vm.synced_folder "..", "/salmon"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "2"
    vb.memory = "1024"
  end

  config.vm.provision "shell", path: "provision/provision.sh"
end
